### PR TITLE
Updated URL for PyQ.

### PR DESCRIPTION
**Pull request by sashkab**

### CODE REVIEW

**Comment by ghost** [comment]
We’ve resolved this now, haven’t we? If you agree, let’s scrap the PR.

**Comment by sashkab** [comment]
@StephenTaylor-Kx -- I didn't check after submitting this PR. Looks like you did. Thanks, closing.

**Comment by sashkab** [comment]
@StephenTaylor-Kx It seems you made the change in the repository, but did not deploy the change to the code.kx.com. Let's keep this open until you deploy. As a workaround we added redirect, but in the future, redirect might be removed and I'd like to avoid 404 errors.

Thanks.

**Comment by ghost** [comment]
Thanks for the catch. Are we there now?

Stephen



Stephen Taylor | Librarian | *Kx* | +44 7713 400852 | stephen@kx.com

**Pull request closed without merging**
