### PR TITLE
add C API reference (#16)

### PR DESCRIPTION
**Pull request by ghost**
* add C API reference
* fixes
* update accessor types

Unresolved: do we need both articles: _C API reference_ and _C client for kdb+_. Seems to be a lot of overlap. 

Also: for constructor functions such as `kz` how does the numeric argument relate to the timestamp required?

### CODE REVIEW

**Comment by abalkin** [comment]
> Also: for constructor functions such as kz how does the numeric argument relate to the timestamp required?

Sorry, I could not help but to show off pyq:

```python
>>> K._kz(1.5)
k('2000.01.02T12:00:00.000')
```
The numerical argument is the day number (with 0 corresponding to 2000.01.01) plus a fraction of the day.  So that .0 is midnight and .5 is noon.

Note that the datetime type is deprecated and if you want to document it at all – please mention that the timestamp type should be used instead.

**Comment by abalkin** [comment]
> Unresolved: do we need both articles: C API reference and C client for kdb+. Seems to be a lot of overlap.

I would say: yes.  In the Python documentation, we have [Extending and Embedding](https://docs.python.org/3/extending/index.html) tutorial and [Python/C API](https://docs.python.org/3/c-api/index.html) reference separately and it works well.

**Comment by ghost** [comment]
So should [C client for kdb](http://code.kx.com/q/interfaces/c-client-for-q/)+ move to the Tutorials section?

**Comment by abalkin** [comment]
I would rather see one chapter dedicated to C that will have a separate section with the API reference, two separate sections on building a client app and a server extension and maybe a tutorial with practical examples.  This seems to be the way Fusion interfaces are documented.  In any case the C client section should be next to the C API section.

**Comment by ghost** [comment]
Now published.

**Pull request closed without merging**
