### PR TITLE
add missing errors

### PR DESCRIPTION
**Pull request by sv**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Sorry for delay – vacation. Thanks for this. Could we keep the rows in alphabetical order?

**Comment by sv** [comment]
Sure, didn't realise they are in alphabetical order...
There are 2 error lists - second one is here http://code.kx.com/q/ref/error-list/

Please delete this one in favour of Simon's and I can update that one

**Comment by StephenTaylor-Kx** [comment]
I hadn’t stopped to compare them – really? Just replace the list from the
wiki with Simon’s?

(Will get back to this on Wednesday.)



Stephen Taylor | Librarian | *Kx* | +44 7713 400852 | stephen@kx.com

**Comment by sv** [comment]
updated with sorting

**Review by ghost — APPROVED** [review]

**Pull request merged**
