### PR TITLE
Added documentation for some of the newer PyQ features.

### PR DESCRIPTION
**Pull request by abalkin**

### CODE REVIEW

**Comment by abalkin** [comment]
@StephenTaylor-Kx - please review.  I did not try to build the docs with these changes, but I hope I got the markdown right.  Please check that the tip box on "Extras" shows up correctly.

**Comment by ghost** [comment]
Looks like your text editor is set to discard trailing spaces. This is not a safe setting for our Markdown, because a trailing double space (yuk) marks a forced line break. Also generates a lot of spurious changes in the diff. I think I found your intende change and it looks OK, so merging this.

**Comment by ghost** [comment]
Merged locally and pushed to server

**Comment by ghost** [comment]
Slight fix to the admonition: the title string needed embracing
double-quotes. Thanks for this!

Best
Stephen



Stephen Taylor | Librarian | *Kx* | +44 7713 400852 | stephen@kx.com

**Pull request merged**
